#!/bin/bash

DATE=`date +%Y%m%d%H%M%S`

unameOut="$(uname -s)"
case "${unameOut}" in
    Linux*)     machine="Linux";;
    Darwin*)    machine="Mac";;
    CYGWIN*)    machine="Cygwin";;
    MINGW*)     machine="MinGw";;
    *)          machine="UNKNOWN:${unameOut}"
esac

cd ~/

if [ -f ~/.vimrc ]; then
    mv ~/.vimrc ~/.vimrc_"$DATE"
fi

if [ -d ~/.vim ]; then
    mv ~/.vim ~/.vim_"$DATE"
fi


#
#	instalar pathogen
#
mkdir -p ~/.vim/autoload ~/.vim/bundle
curl -LSso ~/.vim/autoload/pathogen.vim https://tpo.pe/pathogen.vim
echo "
execute pathogen#infect()
syntax on
filetype plugin indent on
" > ~/.vimrc


#
#	install CTRLP
#
git clone https://github.com/ctrlpvim/ctrlp.vim.git ~/.vim/bundle/ctrlp.vim
echo "
\" CTRLP
set runtimepath^=~/.vim/bundle/ctrlp.vim
let g:ctrlp_prompt_mappings = {
    \ 'AcceptSelection("e")': ['<2-LeftMouse>'],
    \ 'AcceptSelection("t")': ['<cr>'],
    \ }
let g:ctrlp_cmd = 'CtrlPCurWD'"  >> ~/.vimrc 


#
#   install NERDTREE
#
git clone https://github.com/scrooloose/nerdtree.git ~/.vim/bundle/nerdtree
git clone https://github.com/jistr/vim-nerdtree-tabs.git ~/.vim/bundle/vim-nerdtree-tabs
echo "
\" NERDTREE
let g:nerdtree_tabs_open_on_console_startup=1
function! IsNerdTreeEnabled()
    return exists('t:NERDTreeBufName') && bufwinnr(t:NERDTreeBufName) != -1
endfunction
nmap <F7> :NERDTreeTabsToggle<CR>"  >> ~/.vimrc
if [ "Linux" == "$machine" ]; then
    echo "let NERDTreeDirArrowExpandable='+'"  >> ~/.vimrc
    echo "let NERDTreeDirArrowCollapsible='-'"  >> ~/.vimrc
fi


#
#   install THEME
#
git clone https://github.com/kristijanhusak/vim-hybrid-material ~/.vim/bundle/vim-hybrid-material
echo "
\" THEME
set background=dark
colorscheme hybrid_reverse
set cursorline
set cursorcolumn"  >> ~/.vimrc 

#
#  install indent guides
#
git clone https://github.com/nathanaelkane/vim-indent-guides.git ~/.vim/bundle/vim-indent-guides
echo "
\" INDENT GUIDES
let g:indent_guides_enable_on_vim_startup = 1
autocmd VimEnter,Colorscheme * :hi IndentGuidesOdd  guibg=red   ctermbg=3
autocmd VimEnter,Colorscheme * :hi IndentGuidesEven guibg=green ctermbg=4
let g:indent_guides_guide_size=1
let g:indent_guides_start_level=2
set ts=4 sw=4 et
"  >> ~/.vimrc       


#
# TagBar
#
if [ "Mac" == "$machine" ]; then
    git clone https://github.com/majutsushi/tagbar  ~/.vim/bundle/tagbar
    brew tap universal-ctags/universal-ctags
    xcode-select --install
    brew install --HEAD universal-ctags/universal-ctags/universal-ctags
    echo "
\" TAGBAR
let g:tagbar_autoclose=1
nmap <F8> :TagbarToggle<CR>"  >> ~/.vimrc  

fi

#
# VUE SYNTAX
#
git clone https://github.com/posva/vim-vue.git ~/.vim/bundle/vim-vue

#
# VOLT SYNTAX
#
git clone https://github.com/etaoins/vim-volt-syntax ~/.vim/bundle/vim-volt-syntax 
echo "au BufReadPost *.volt.php set syntax=volt"  >> ~/.vimrc 

curl "https://vim.sourceforge.io/scripts/download_script.php\?src_id\=4666" >> ~/.vim/php-doc.vim 
echo "
\" phpDoc
source ~/.vim/php-doc.vim 
inoremap <C-C> <ESC>:call PhpDocSingle()<CR>i 
nnoremap <C-C> :call PhpDocSingle()<CR> 
vnoremap <C-C> :call PhpDocRange()<CR> 

let g:pdv_cfg_Package = ""
let g:pdv_cfg_Version = ""
let g:pdv_cfg_Author="Márcio Padinha Brandão <mbrandao@bsolus.pt>"
let g:pdv_cfg_Copyright = ""
let g:pdv_cfg_License = ""
"  >> ~/.vimrc 

git clone https://github.com/Xuyuanp/nerdtree-git-plugin.git ~/.vim/bundle/nerdtree-git-plugin
git clone git://github.com/airblade/vim-gitgutter.git ~/.vim/bundle/vim-gitgutter
git clone https://github.com/tpope/vim-fugitive.git ~/.vim/bundle/vim-fugitive

#
#
#
echo "
\" set relativenumber
set number relativenumber

set so=99999
set tabstop=4 softtabstop=0 expandtab shiftwidth=4 smarttab
set ruler
\" set statusline+=%F\\ %l\\:%c
set statusline=%<%{fugitive#statusline()}%P\ %l,%c\ %h%m%r%f%=%{strftime(\\\"%Y-%m-%d\ %l:%M:%S\\\")}
set statusline=%<%P\ %l,%c\ %h%m%r%f%=%{strftime(\\\"%Y-%m-%d\ %l:%M:%S\\\")}
hi statusline guibg=Cyan ctermfg=6 guifg=Black ctermbg=White

\" habilitar insert(paste) por defeito
set paste
augroup scroll
    au!
    au  VimEnter * :silent !synclient VertEdgeScroll=0
    au  VimLeave * :silent !synclient VertEdgeScroll=1
augroup END

\" vim-gitgutter
set updatetime=250
"  >> ~/.vimrc 


echo "Done!"
